global:
  ignore_config: false

post:
  quote_source: QUOTE_API # QUOTE_API
  img_search: QUOTE_BASED # THEME_BASED|QUOTE_BASED
  img_api: unsplash # unsplash|google
  profile_name: "@the.wisdom.drops"
  output_size: [1080, 1080]
  ignore_used_quotes: true
  ignore_used_imgs: true
  txt_aspect_ratio: NARROW # NARROW|WIDE
  txt_word_count: 16
  font_family: Poppins # Arial|DancingScript|Georgia|Montserrat|Poppins
  font_style: Bold # Bold|Italic|Light
  font_color: AUTO # AUTO (or hex values)
  img_format: PNG
  overlay: "OVERLAY_80%OP_BLACK_BOTTOM_LEFT_SOFT"
  lang: english # 'english'
  posts_per_theme: "[IGNORE]"

text:
  blurred_halo: true
  blur_radius: 10
  padding_pct: 0.25

computer-vision:
  thresh: "[IGNORE]"
  area_to_keep_free: LEFT # LEFT|RIGHT

image:
  sat: "[IGNORE]"
  pct: "[IGNORE]"
  quality: "[IGNORE]"
  color_count: "[IGNORE]"
  brightness: "[IGNORE]"
  bottom_right_txt: " "
  top_right_txt: " "
  padding: 40
  txt_brightness: 3
  font_size: 50
